import { SiBitcoin, SiEthereum } from 'react-icons/si';
import { AiOutlineEuro } from 'react-icons/ai';
import { RiPieChartFill } from 'react-icons/ri';

export const ALL_ASSETS = [
	{
		name: 'Bitcoin',
		symbol: 'BTC',
		isFiat: false,
		icon: <SiBitcoin />,
		balance_eur: 10986.74,
		balance_coin: 0.84433661,
		price_eur: 10.38,
		price_change24h: -3.9,
		market_cap: 90.66,
		onWatchlist: false,
	},
	{
		name: 'Ethereum',
		symbol: 'ETH',
		isFiat: false,
		icon: <SiEthereum />,
		balance_eur: 6986.74,
		balance_coin: 10.844336,
		price_eur: 58.38,
		price_change24h: 2.1,
		market_cap: 45.66,
		onWatchlist: true,
	},
	{
		name: 'Cardano',
		symbol: 'ADA',
		isFiat: false,
		icon: <RiPieChartFill />,
		balance_eur: 2986.74,
		balance_coin: 0.84433661,
		price_eur: 10.38,
		price_change24h: -3.9,
		market_cap: 19.66,
		onWatchlist: false,
	},
	{
		name: 'Solana',
		symbol: 'SOL',
		isFiat: false,
		icon: <RiPieChartFill />,
		balance_eur: 1086.74,
		balance_coin: 10.844336,
		price_eur: 58.38,
		price_change24h: 2.1,
		market_cap: 11.66,
		onWatchlist: false,
	},
	{
		name: 'Avalance',
		symbol: 'AVA',
		isFiat: false,
		icon: <RiPieChartFill />,
		balance_eur: 3986.74,
		balance_coin: 0.84433661,
		price_eur: 10.38,
		price_change24h: -3.9,
		market_cap: 9.66,
		onWatchlist: false,
	},
	{
		name: 'Dogecoin',
		symbol: 'DOGE',
		isFiat: false,
		icon: <RiPieChartFill />,
		balance_eur: 986.74,
		balance_coin: 10.844336,
		price_eur: 58.38,
		price_change24h: 2.1,
		market_cap: 8.66,
		onWatchlist: false,
	},
	{
		name: 'Polkadot',
		symbol: 'DOT',
		isFiat: false,
		icon: <RiPieChartFill />,
		balance_eur: 786.74,
		balance_coin: 0.84433661,
		price_eur: 10.38,
		price_change24h: -3.9,
		market_cap: 9.66,
		onWatchlist: false,
	},
	{
		name: 'SHIBA INU',
		symbol: 'SHIB',
		isFiat: false,
		icon: <RiPieChartFill />,
		balance_eur: 586.74,
		balance_coin: 10.844336,
		price_eur: 58.38,
		price_change24h: 2.1,
		market_cap: 19.66,
		onWatchlist: true,
	},
	{
		name: 'Trashcoin',
		symbol: 'TRA',
		isFiat: false,
		icon: <RiPieChartFill />,
		balance_eur: 0,
		balance_coin: 0,
		price_eur: 28.38,
		price_change24h: -52.1,
		market_cap: 7.2,
		onWatchlist: true,
	},
	{
		name: 'Worldcoin',
		symbol: 'WLD',
		isFiat: false,
		icon: <RiPieChartFill />,
		balance_eur: 0,
		balance_coin: 0,
		price_eur: 38.38,
		price_change24h: 20.1,
		market_cap: 0.66,
		onWatchlist: true,
	},
	,
	{
		name: 'Euro',
		symbol: 'EUR',
		isFiat: true,
		icon: <AiOutlineEuro />,
		balance_eur: 2500,
		balance_coin: 0,
		price_eur: 38.38,
		price_change24h: 20.1,
		market_cap: 0.66,
		onWatchlist: true,
	},
];
