export const PAYMENTS = [
  {
    id: 1,
    adress: 'satoshi@gmail.com',
    name: 'Bitcoin',
    symbol: 'BTC',
    icon: 'https://cdn.coinranking.com/bOabBYkcX/bitcoin_btc.svg',
    type: 'send',
    date: 'Oct 19, 2021',
    amount: 0.432565,
  },
  {
    id: 2,
    adress: 'elon.musk@yahoo.com',
    name: 'Bitcoin',
    symbol: 'BTC',
    icon: 'https://cdn.coinranking.com/bOabBYkcX/bitcoin_btc.svg',
    type: 'send',
    date: 'Oct 21, 2021',
    amount: 17.432565,
  },
  {
    id: 3,
    adress: 'vitalik@buterin.com',
    name: 'Etheruem',
    symbol: 'ETH',
    icon: 'https://cdn.coinranking.com/bOabBYkcX/bitcoin_btc.svg',
    type: 'send',
    date: 'Nov 03, 2021',
    amount: 70.432565,
  },
];
